<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="test.testng.TestAddition" tests="6" time="0.041" ignored="5" failures="2" timestamp="28 Jan 2020 14:10:30 GMT" skipped="0" hostname="DESKTOP-L2VJL3A" errors="0">
  <testcase name="testaddition" time="0.033" classname="test.testng.TestAddition"/>
  <testcase name="testaddition" time="0.000" classname="test.testng.TestAddition"/>
  <testcase name="testaddition" time="0.000" classname="test.testng.TestAddition"/>
  <testcase name="testaddition" time="0.007" classname="test.testng.TestAddition">
    <failure type="java.lang.AssertionError" message="expected [11] but found [9]">
      <![CDATA[java.lang.AssertionError: expected [11] but found [9]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at test.testng.TestAddition.testaddition(TestAddition.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testaddition -->
  <testcase name="testaddition" time="0.000" classname="test.testng.TestAddition">
    <failure type="java.lang.AssertionError" message="expected [11] but found [9]">
      <![CDATA[java.lang.AssertionError: expected [11] but found [9]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at test.testng.TestAddition.testaddition(TestAddition.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testaddition -->
  <testcase name="testaddition" time="0.001" classname="test.testng.TestAddition"/>
  <testcase name="testexception1" classname="test.testng.TestExceptions">
    <skipped/>
  </testcase> <!-- testexception1 -->
  <testcase name="testMethod2" classname="test.testng.AppTest">
    <skipped/>
  </testcase> <!-- testMethod2 -->
  <testcase name="testmethod4" classname="test.testng.AppTest">
    <skipped/>
  </testcase> <!-- testmethod4 -->
  <testcase name="testmethod5" classname="test.testng.AppTest">
    <skipped/>
  </testcase> <!-- testmethod5 -->
  <testcase name="testMethod3" classname="test.testng.AppTest">
    <skipped/>
  </testcase> <!-- testMethod3 -->
</testsuite> <!-- test.testng.TestAddition -->
